# gültig, wenn kein explizites Profil aktiviert wird
# potientiell: Datasource
spring:
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:9080/h2-console (leave username and password empty)
application:
  initialize-sample-data-on-startup: true
